name = "pem-tracker-api"
main = "workers/index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "KV"
id = "63cf2597c1c04ae398d37a906a16b45f"

[triggers]
crons = ["*/30 * * * *"]

# Secrets (set via: npx wrangler secret put VAPID_PUBLIC_KEY etc.)
# VAPID_PUBLIC_KEY
# VAPID_PRIVATE_KEY
# VAPID_SUBJECT
